### ISSUE TITLE
Linter exception while using dart-tools

### ISSUE THREAD

**Issue by alechenninger** [radicaled/dart-tools#98] opened 2015-07-08 23:31 UTC
Please see https://github.com/AtomLinter/Linter/issues/713

Not sure if this is issue with dart-tools and/or linter, but linter works fine for non-dart projects.

**Comment by radicaled** [comment] 2015-07-08 23:33
Looks like a regression on their side.

**Comment by alechenninger** [comment] 2015-07-08 23:35
Yeah I think you're right, thanks for quick response

**Comment by radicaled** [comment] 2015-07-08 23:37
Gonna leave this open so incoming users will know it's broken.

**Comment by alechenninger** [comment] 2015-07-08 23:40
Ack, cool. I downgraded linter to 1.1.0 and no issues.

**Comment by devoncarew** [comment] 2015-07-08 23:43
I suspect they changed their API for the linter:

https://github.com/AtomLinter/Linter/blob/a292cd757489d6a3ddc70a7e03c5d127e285b587/lib/linter-plus.coffee#L90

**Comment by radicaled** [comment] 2015-07-08 23:46
It's the line below that: they're referencing a non-existent variable.

**Comment by radicaled** [comment] 2015-07-08 23:46
Someone fudged a refactor, in other words.

**Comment by radicaled** [comment] 2015-07-08 23:50
@alechenninger grab the newest dart-tools and it should be fixed. I've gone ahead and quickly upgraded to their working API

**Comment by alechenninger** [comment] 2015-07-08 23:52
Thanks! With the latest version of linter and dart-tools running the analyzer works fine with no exceptions. :+1:

**Comment by radicaled** [comment] 2015-07-08 23:53
Great! Now I'll close the issue. :)

**Closed by radicaled** 2015-07-08 23:53 UTC
